% Average RDMs across subject per vertex per time point.
% Created by Li Su, last updated 24 Nov 2010

clear all;
close all;

subjectIDs = { ...
		'08_0319', ...
        '08_0320', ...      
		'08_0323', ...
		'08_0324', ...	
		'08_0327', ...
		'08_0348', ...		
		'08_0350', ... 
		'08_0363', ...
		'08_0366', ...
        '08_0371', ...
        '08_0372', ...    
		'08_0377', ...
		'08_0380', ...	
		'08_0397', ...
		'08_0400', ...		
		'08_0401', ...
		'08_0402'};
numberOfSubjects = size(subjectIDs,2);

modelName = 'phono_weak';

subjectPath = ['nodepth/played_trade_cream/RFX/',modelName, '/'];

disp(['  Averaging RDMs for subject ' subjectIDs{1} '...']);
% loading subject RDM data
subjectFileName = [subjectPath, 'meg', subjectIDs{1}, '-r_value-', modelName];
averageL = mne_read_stc_file([subjectFileName,'-lh.stc']);
averageR = mne_read_stc_file([subjectFileName,'-rh.stc']);

for subject = 2:numberOfSubjects
    disp(['  Averaging RDMs for subject ' subjectIDs{subject} '...']);
        % loading subject RDM data
    subjectFileName = [subjectPath, 'meg', subjectIDs{subject}, '-r_value-', modelName];
    thisL = mne_read_stc_file([subjectFileName,'-lh.stc']);
    thisR = mne_read_stc_file([subjectFileName,'-rh.stc']);
    averageL.data = averageL.data + thisL.data;
    averageR.data = averageR.data + thisR.data;
end

averageL.data = averageL.data ./ numberOfSubjects;
averageR.data = averageR.data ./ numberOfSubjects;

mne_write_stc_file([subjectPath,'G_average_r_map-', modelName, '-lh.stc'],averageL);
mne_write_stc_file([subjectPath,'G_average_r_map-', modelName, '-rh.stc'],averageR);